# online 
env_id: "CarRacing-v2"
gamma: 0.99
tau: 0.005
auto_alpha: True
alpha: 0.2
batch_size: 128
hidden_state: 256
n_channels: 4
img_size: 96
chkpt_dir: "models/online_auto"
lr_actor: 1.e-4
lr_critic: 1.e-4
hidden_size: 256
memory_size: 20000
n_episode: 3000
start_steps: 1000
log_dir: "log"
experiment_name: "online"
load_checkpoint: False
save_memory: False
memory_dir: "memory_3"
save_interval: 5

